/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vendalancha.view;

import com.vendalancha.control.VendedorController;
import com.vendalancha.dao.VendedorDAO;
import com.vendalancha.model.Vendedor;
import com.vendalancha.util.IconeUtil;
import com.vendalancha.util.validacao.ValidacaoEntrada;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author User
 */
public class TelaExibicaoVendedores extends javax.swing.JFrame {

    /**
     * Creates new form TelaExibicaoVendedores
     */
    public TelaExibicaoVendedores() {
        initComponents();
        jt_tabelaVendedores.setRowHeight(30);
        estilizarHeader();
        carregarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt_tabelaVendedores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnDeletar = new javax.swing.JButton();
        jb_editar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jt_tabelaVendedores.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jt_tabelaVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Nome de Usuário", "Salário"
            }
        ));
        jt_tabelaVendedores.setAlignmentX(1.0F);
        jt_tabelaVendedores.setAlignmentY(1.0F);
        jt_tabelaVendedores.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(jt_tabelaVendedores);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Lista de Vendedores");

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vendalancha/imagens/voltar32.png"))); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N

        btnDeletar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vendalancha/imagens/not-ok32.png"))); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        jb_editar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jb_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vendalancha/imagens/edit32.png"))); // NOI18N
        jb_editar.setText("Editar Salário");
        jb_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_editarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vendalancha/imagens/vendedor128.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jButton2)
                        .addGap(33, 33, 33)
                        .addComponent(btnDeletar)
                        .addGap(48, 48, 48)
                        .addComponent(jb_editar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDeletar, jButton2, jb_editar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(btnDeletar)
                            .addComponent(jb_editar))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDeletar, jButton2, jb_editar});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
        int linha = jt_tabelaVendedores.getSelectedRow();
        
        if(linha >= 0){
            String usuario = jt_tabelaVendedores.getValueAt(linha, 1).toString();
            int confirmacao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja deletar o vendedor " + usuario + "?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (confirmacao == JOptionPane.YES_OPTION) {
                if(VendedorController.deletarVendedor(usuario)){
                    carregarDados(); // Atualiza a tabela
                    JOptionPane.showMessageDialog(rootPane, "Deletado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE, IconeUtil.getIconeSucesso());
                } else{
                    JOptionPane.showMessageDialog(rootPane, "Um erro inesperado aconteceu.", "Erro", JOptionPane.INFORMATION_MESSAGE, IconeUtil.getIconeErro());
                }
            }
        } 
        else{
            // não foi selecionado vendedor para ser deletado
            JOptionPane.showMessageDialog(rootPane, "Selecione um vendedor", "Erro: nenhum vendedor selecionado", JOptionPane.ERROR_MESSAGE, IconeUtil.getIconeErro());
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void jb_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_editarActionPerformed
        // TODO add your handling code here:
        int linha = jt_tabelaVendedores.getSelectedRow();
        if(linha >= 0){
            String usuario = jt_tabelaVendedores.getValueAt(linha, 1).toString();
            String str_salarioAntigo = jt_tabelaVendedores.getValueAt(linha, 2).toString().replace(",", ".");            
            String str_novoSalario = JOptionPane.showInputDialog("Insira o novo salário de " + usuario);
           
            if(str_novoSalario == null) return; // usuário desistiu de editar o salário
            str_novoSalario = str_novoSalario.replace(",", "."); // usuário pode utilizar ',' ou '.' para representar parte decimal
            
            int mensagem = VendedorController.alterarSalario(usuario, str_salarioAntigo, str_novoSalario);
            switch(mensagem){
                case 1 -> {
                    JOptionPane.showMessageDialog(rootPane, "Salário alterado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE, IconeUtil.getIconeSucesso());
                    double novoSalario = Double.parseDouble(str_novoSalario);
                    jt_tabelaVendedores.setValueAt(String.format("%.2f", novoSalario), linha, 2);
                }
                case 2 -> {
                    JOptionPane.showMessageDialog(rootPane, "Salário deve ser um valor númerico.", "Erro: salário inválido", JOptionPane.ERROR_MESSAGE, IconeUtil.getIconeErro());
                }
                case 3 -> {
                    JOptionPane.showMessageDialog(rootPane, "Salário deve ser superior ao salário antigo.", "Erro: salário inferior ao anterior", JOptionPane.ERROR_MESSAGE, IconeUtil.getIconeErro()); 
                }
                case 4 -> {
                    JOptionPane.showMessageDialog(rootPane, "Um erro inesperado aconteceu..", "Erro", JOptionPane.ERROR_MESSAGE, IconeUtil.getIconeErro()); 
                }
            }
        } else{
            // nenhum vendedor selecionado
            JOptionPane.showMessageDialog(rootPane, "Selecione um vendedor", "Erro: nenhum vendedor selecionado", JOptionPane.ERROR_MESSAGE, IconeUtil.getIconeErro());            
        }
    }//GEN-LAST:event_jb_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExibicaoVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExibicaoVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExibicaoVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExibicaoVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExibicaoVendedores().setVisible(true);
            }
        });
    }
    
    private void estilizarHeader(){
        JTableHeader header = jt_tabelaVendedores.getTableHeader();
        header.setFont(new Font("Comic Sans MS", Font.BOLD, 15));
        header.setBackground(new Color(173,216,230));
        header.setForeground(Color.BLACK);
    }
    
    private void carregarDados(){
        ArrayList<Vendedor> vendedores = VendedorDAO.carregarVendedores();
        
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Nenhuma célula será editável
            }
        };
        modelo.addColumn("Nome Completo");
        modelo.addColumn("Usuário");
        modelo.addColumn("Salário");

        for (Vendedor v : vendedores) {
            modelo.addRow(new Object[]{
                v.getNomeCompleto(),
                v.getNomeUsuario(),
                String.format("%.2f", v.getSalario())
            });
        }

        jt_tabelaVendedores.setModel(modelo);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_editar;
    private javax.swing.JTable jt_tabelaVendedores;
    // End of variables declaration//GEN-END:variables

    private Vendedor Vendedor() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
