/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vendalancha.view;

import com.vendalancha.view.cadastro.TelaCadastroVendedor;
import com.vendalancha.model.Gerente;
import com.vendalancha.view.cadastro.TelaCadastroBarco;
import com.vendalancha.view.cadastro.TelaCadastroLancha;
import com.vendalancha.view.cadastro.TelaCadastroViagem;
import javax.swing.JFrame;

/**
 *
 * @author User
 */
public class TelaGerente extends javax.swing.JFrame {
    private Gerente gerente;

    /**
     * Creates new form TelaADM
     * @param gerente
     */
    public TelaGerente(Gerente gerente) {
        this.gerente = gerente;
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);  // utilizar a tela inteira
        label_nomeGerente.setText(gerente.getNomeUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        label_nomeGerente = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mn_vendedor = new javax.swing.JMenu();
        mi_cadastrarVendedor = new javax.swing.JMenuItem();
        mi_visualizarVendedor = new javax.swing.JMenuItem();
        mn_embarcacao = new javax.swing.JMenu();
        mi_cadastrarBarco = new javax.swing.JMenuItem();
        mi_cadastrarLancha = new javax.swing.JMenuItem();
        mi_visualizarBarcos = new javax.swing.JMenuItem();
        mi_visualizarLanchas = new javax.swing.JMenuItem();
        mn_viagem = new javax.swing.JMenu();
        mi_cadastrarViagem = new javax.swing.JMenuItem();
        mi_visualizarViagens = new javax.swing.JMenuItem();
        mn_vender = new javax.swing.JMenu();
        mi_venderPassagem = new javax.swing.JMenuItem();
        mn_configuracoes = new javax.swing.JMenu();
        mi_alterarUser = new javax.swing.JMenuItem();
        mi_alterarSenha = new javax.swing.JMenuItem();
        mn_voltar = new javax.swing.JMenu();
        mi_login = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(176, 196, 222));

        label_nomeGerente.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1098, Short.MAX_VALUE)
                .addComponent(label_nomeGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(650, Short.MAX_VALUE)
                .addComponent(label_nomeGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jMenuBar1.setAlignmentX(1.0F);
        jMenuBar1.setAlignmentY(0.5F);
        jMenuBar1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(2, 2, 2, 2));

        mn_vendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vendalancha/imagens/vendedor32.png"))); // NOI18N
        mn_vendedor.setText("Vendedor");
        mn_vendedor.setAlignmentX(1.0F);
        mn_vendedor.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        mn_vendedor.setIconTextGap(10);
        mn_vendedor.setMargin(new java.awt.Insets(10, 8, 10, 8));

        mi_cadastrarVendedor.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mi_cadastrarVendedor.setText("Cadastrar");
        mi_cadastrarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_cadastrarVendedorActionPerformed(evt);
            }
        });
        mn_vendedor.add(mi_cadastrarVendedor);

        mi_visualizarVendedor.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mi_visualizarVendedor.setText("Visualizar");
        mi_visualizarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_visualizarVendedorActionPerformed(evt);
            }
        });
        mn_vendedor.add(mi_visualizarVendedor);

        jMenuBar1.add(mn_vendedor);

        mn_embarcacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vendalancha/imagens/lancha32.png"))); // NOI18N
        mn_embarcacao.setText("Embarcação");
        mn_embarcacao.setAlignmentX(1.0F);
        mn_embarcacao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mn_embarcacao.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        mn_embarcacao.setIconTextGap(10);
        mn_embarcacao.setMargin(new java.awt.Insets(10, 8, 10, 8));
        mn_embarcacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_embarcacaoActionPerformed(evt);
            }
        });

        mi_cadastrarBarco.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mi_cadastrarBarco.setText("Cadastrar Barco");
        mi_cadastrarBarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_cadastrarBarcoActionPerformed(evt);
            }
        });
        mn_embarcacao.add(mi_cadastrarBarco);

        mi_cadastrarLancha.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mi_cadastrarLancha.setText("Cadastrar Lancha");
        mi_cadastrarLancha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_cadastrarLanchaActionPerformed(evt);
            }
        });
        mn_embarcacao.add(mi_cadastrarLancha);

        mi_visualizarBarcos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mi_visualizarBarcos.setText("Visualizar Barcos");
        mi_visualizarBarcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_visualizarBarcosActionPerformed(evt);
            }
        });
        mn_embarcacao.add(mi_visualizarBarcos);

        mi_visualizarLanchas.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mi_visualizarLanchas.setText("Visualizar Lanchas");
        mi_visualizarLanchas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_visualizarLanchasActionPerformed(evt);
            }
        });
        mn_embarcacao.add(mi_visualizarLanchas);

        jMenuBar1.add(mn_embarcacao);

        mn_viagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vendalancha/imagens/mapa32.png"))); // NOI18N
        mn_viagem.setText("Viagem");
        mn_viagem.setAlignmentX(1.0F);
        mn_viagem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mn_viagem.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        mn_viagem.setIconTextGap(10);
        mn_viagem.setMargin(new java.awt.Insets(10, 8, 10, 8));

        mi_cadastrarViagem.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mi_cadastrarViagem.setText("Cadastrar");
        mi_cadastrarViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_cadastrarViagemActionPerformed(evt);
            }
        });
        mn_viagem.add(mi_cadastrarViagem);

        mi_visualizarViagens.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mi_visualizarViagens.setText("Visualizar");
        mn_viagem.add(mi_visualizarViagens);

        jMenuBar1.add(mn_viagem);

        mn_vender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vendalancha/imagens/passagem32.png"))); // NOI18N
        mn_vender.setText("Vender");
        mn_vender.setAlignmentX(1.0F);
        mn_vender.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mn_vender.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        mn_vender.setIconTextGap(10);
        mn_vender.setMargin(new java.awt.Insets(10, 8, 10, 8));

        mi_venderPassagem.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mi_venderPassagem.setText("Passagem");
        mn_vender.add(mi_venderPassagem);

        jMenuBar1.add(mn_vender);

        mn_configuracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vendalancha/imagens/admin32.png"))); // NOI18N
        mn_configuracoes.setText("Configurações");
        mn_configuracoes.setAlignmentX(1.0F);
        mn_configuracoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mn_configuracoes.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        mn_configuracoes.setIconTextGap(10);
        mn_configuracoes.setMargin(new java.awt.Insets(10, 8, 10, 8));

        mi_alterarUser.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mi_alterarUser.setText("Alterar Nome de Usuário");
        mn_configuracoes.add(mi_alterarUser);

        mi_alterarSenha.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mi_alterarSenha.setText("Alterar Senha");
        mi_alterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_alterarSenhaActionPerformed(evt);
            }
        });
        mn_configuracoes.add(mi_alterarSenha);

        jMenuBar1.add(mn_configuracoes);

        mn_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vendalancha/imagens/voltar32.png"))); // NOI18N
        mn_voltar.setText("Voltar");
        mn_voltar.setAlignmentX(1.0F);
        mn_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mn_voltar.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        mn_voltar.setIconTextGap(10);
        mn_voltar.setMargin(new java.awt.Insets(10, 8, 10, 8));

        mi_login.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mi_login.setText("Página Login");
        mi_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_loginActionPerformed(evt);
            }
        });
        mn_voltar.add(mi_login);

        jMenuBar1.add(mn_voltar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mi_alterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_alterarSenhaActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_mi_alterarSenhaActionPerformed

    private void mi_cadastrarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_cadastrarVendedorActionPerformed
        // TODO add your handling code here:
        new TelaCadastroVendedor().setVisible(true);
    }//GEN-LAST:event_mi_cadastrarVendedorActionPerformed

    private void mi_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_loginActionPerformed
        // TODO add your handling code here:
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mi_loginActionPerformed

    private void mi_visualizarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_visualizarVendedorActionPerformed
        // TODO add your handling code here:
        new TelaExibicaoVendedores().setVisible(true);
    }//GEN-LAST:event_mi_visualizarVendedorActionPerformed

    private void mi_cadastrarBarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_cadastrarBarcoActionPerformed
        // TODO add your handling code here:
        new TelaCadastroBarco().setVisible(true);
    }//GEN-LAST:event_mi_cadastrarBarcoActionPerformed

    private void mi_visualizarBarcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_visualizarBarcosActionPerformed
        // TODO add your handling code here:
        new TelaExibicaoBarcos().setVisible(true);
    }//GEN-LAST:event_mi_visualizarBarcosActionPerformed

    private void mi_cadastrarLanchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_cadastrarLanchaActionPerformed
        // TODO add your handling code here:
        new TelaCadastroLancha().setVisible(true);
    }//GEN-LAST:event_mi_cadastrarLanchaActionPerformed

    private void mn_embarcacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_embarcacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mn_embarcacaoActionPerformed

    private void mi_visualizarLanchasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_visualizarLanchasActionPerformed
        // TODO add your handling code here:
        new TelaExibicaoLanchas().setVisible(true);
    }//GEN-LAST:event_mi_visualizarLanchasActionPerformed

    private void mi_cadastrarViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_cadastrarViagemActionPerformed
        // TODO add your handling code here:
        new TelaCadastroViagem().setVisible(true);
    }//GEN-LAST:event_mi_cadastrarViagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerente(new Gerente("", "", "")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_nomeGerente;
    private javax.swing.JMenuItem mi_alterarSenha;
    private javax.swing.JMenuItem mi_alterarUser;
    private javax.swing.JMenuItem mi_cadastrarBarco;
    private javax.swing.JMenuItem mi_cadastrarLancha;
    private javax.swing.JMenuItem mi_cadastrarVendedor;
    private javax.swing.JMenuItem mi_cadastrarViagem;
    private javax.swing.JMenuItem mi_login;
    private javax.swing.JMenuItem mi_venderPassagem;
    private javax.swing.JMenuItem mi_visualizarBarcos;
    private javax.swing.JMenuItem mi_visualizarLanchas;
    private javax.swing.JMenuItem mi_visualizarVendedor;
    private javax.swing.JMenuItem mi_visualizarViagens;
    private javax.swing.JMenu mn_configuracoes;
    private javax.swing.JMenu mn_embarcacao;
    private javax.swing.JMenu mn_vendedor;
    private javax.swing.JMenu mn_vender;
    private javax.swing.JMenu mn_viagem;
    private javax.swing.JMenu mn_voltar;
    // End of variables declaration//GEN-END:variables
}
