/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vendalancha.view;

import com.vendalancha.control.BarcoController;
import com.vendalancha.dao.BarcoDAO;
import com.vendalancha.model.Barco;
import com.vendalancha.util.IconeUtil;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author User
 */
public class TelaExibicaoBarcos extends javax.swing.JFrame {

    /**
     * Creates new form TelaExibicaoEmbarcacoes
     */
    public TelaExibicaoBarcos() {
        initComponents();
        jt_tabelaBarcos.setRowHeight(30);
        estilizarHeader();
        carregarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_tabelaBarcos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btn_deletar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Lista de Barcos");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N

        jScrollPane1.setBorder(null);

        jt_tabelaBarcos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jt_tabelaBarcos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Tipo", "Nº Redes", "Nº Camarotes", "Nº Poltronas"
            }
        ));
        jt_tabelaBarcos.setAlignmentX(1.0F);
        jt_tabelaBarcos.setAlignmentY(1.0F);
        jScrollPane1.setViewportView(jt_tabelaBarcos);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vendalancha/imagens/barco128.png"))); // NOI18N

        btnVoltar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vendalancha/imagens/voltar32.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btn_deletar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btn_deletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vendalancha/imagens/not-ok32.png"))); // NOI18N
        btn_deletar.setText("Deletar");
        btn_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletarActionPerformed(evt);
            }
        });

        btn_editar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vendalancha/imagens/edit32.png"))); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(62, 62, 62)
                        .addComponent(btn_deletar)
                        .addGap(56, 56, 56)
                        .addComponent(btn_editar)
                        .addGap(150, 150, 150))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnVoltar, btn_deletar, btn_editar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addGap(58, 58, 58))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btn_deletar)
                    .addComponent(btn_editar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnVoltar, btn_deletar, btn_editar});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        int linha = jt_tabelaBarcos.getSelectedRow();
        if(linha >= 0){
            String nomeBarco = jt_tabelaBarcos.getValueAt(linha, 0).toString();
            int nRedes = Integer.parseInt(jt_tabelaBarcos.getValueAt(linha, 1).toString());
            int nCamarotes = Integer.parseInt(jt_tabelaBarcos.getValueAt(linha, 2).toString());
            int nAndares = Integer.parseInt(jt_tabelaBarcos.getValueAt(linha, 3).toString());
             
            Barco barco = new Barco(nomeBarco, nRedes, nCamarotes, nAndares);
            TelaEdicaoBarco telaEdicao = new TelaEdicaoBarco(barco);
            telaEdicao.setVisible(true);
            telaEdicao.addWindowListener(new java.awt.event.WindowAdapter() {
            
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                carregarDados(); // Só atualiza a tabela depois que a janela de edição for fechada
            }
            });
            
            return;
        }
        
        JOptionPane.showMessageDialog(rootPane, "Selecione um barco", "Erro: nenhum barco selecionado", JOptionPane.ERROR_MESSAGE, IconeUtil.getIconeErro());
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletarActionPerformed
        // TODO add your handling code here:
        int linha = jt_tabelaBarcos.getSelectedRow();
        if(linha >= 0){
            String nomeBarco = jt_tabelaBarcos.getValueAt(linha, 0).toString();
            int confirmacao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja deletar o barco " + nomeBarco + "?", "Confirmação", JOptionPane.YES_NO_OPTION);
            
            if (confirmacao == JOptionPane.YES_OPTION) {
                if(BarcoController.deletar(nomeBarco)){ 
                    carregarDados(); // 
                    JOptionPane.showMessageDialog(rootPane, "Deletado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE, IconeUtil.getIconeSucesso());
                    return;
                } 
                
                JOptionPane.showMessageDialog(rootPane, "Um erro inesperado aconteceu.", "Erro", JOptionPane.INFORMATION_MESSAGE, IconeUtil.getIconeErro());
            }
            return;
        }
            
        JOptionPane.showMessageDialog(rootPane, "Selecione um barco", "Erro: nenhum barco selecionado", JOptionPane.ERROR_MESSAGE, IconeUtil.getIconeErro());
        
    }//GEN-LAST:event_btn_deletarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExibicaoBarcos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExibicaoBarcos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExibicaoBarcos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExibicaoBarcos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExibicaoBarcos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton btn_deletar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_tabelaBarcos;
    // End of variables declaration//GEN-END:variables
    
    private void estilizarHeader(){
        JTableHeader header = jt_tabelaBarcos.getTableHeader();
        header.setFont(new Font("Comic Sans MS", Font.BOLD, 15));
        header.setBackground(new Color(173,216,230));
        header.setForeground(Color.BLACK);
    }
    
    private void carregarDados(){
        ArrayList<Barco> embarcacoes = BarcoDAO.carregarEmbarcacoes();
        
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Nenhuma célula será editável
            }
        };
        modelo.addColumn("Nome da Embarcação");
        modelo.addColumn("Nº Redes");
        modelo.addColumn("Nº Camarotes");
        modelo.addColumn("Nº Andares");

        for (Barco e : embarcacoes) {
            modelo.addRow(new Object[]{
                e.getNome(),
                e.getnRedes(),
                e.getnCamarotes(),
                e.getnAndares()
            });
        }
        jt_tabelaBarcos.setModel(modelo);
        
    }

}
